/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:18761439-278a-48b9-83cd-7bc2f11b467e",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_xuxi3lCHA",
    "aws_user_pools_web_client_id": "1phjasc0du8mn3m61g37t7p7kg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "prodf65da04098aa4317ae5066c4554e9871134645-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
